### PR TITLE
refactor: add apache 2 license

### PR DESCRIPTION
**Pull request by dimakis**

### CODE REVIEW

**Comment by andreaTP** [comment]
should we remove other `LICENSE` files in the repo, e.g.: https://github.com/redhat-developer/app-services-sdk-core/blob/main/app-services-sdk-java/LICENSE ?

**Comment by dimakis** [comment]
> should we remove other `LICENSE` files in the repo, e.g.: https://github.com/redhat-developer/app-services-sdk-core/blob/main/app-services-sdk-java/LICENSE ?

Do they need to be in the sub dirs for any of the SDK publications?

**Comment by andreaTP** [comment]
> Do they need to be in the sub dirs for any of the SDK release?

no at the best of my knowledge.

**Comment by jackdelahunt** [comment]
They will get removed in my new pr to clean up the repo 👍

**Review by jackdelahunt — APPROVED** [review]

**Review by andreaTP — APPROVED** [review]

**Pull request merged**
